const base = await Deno.readTextFile(
  `${import.meta.dirname}/../runtimes/workerdManager.node.ts`,
);

await Deno.writeTextFile(
  `${import.meta.dirname}/../runtimes/workerdManager.generated.ts`,
  [
    "// deno-lint-ignore-file",
    "// This file is generated by `deno task generateWorkerManager`. DO NOT EDIT THIS FILE MANUALLY.",
    `export default ${JSON.stringify(base)}`,
  ].join("\n"),
);
